package com.aicode.service;

import cn.hutool.core.util.RandomUtil;
import com.aicode.common.exception.BusinessException;
import com.aicode.entity.App;
import com.aicode.mapper.AppMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Slf4j
@Service
@RequiredArgsConstructor
public class ShareService {

    private final AppMapper appMapper;
    private final AppService appService;

    @Value("${server.port:8080}")
    private int serverPort;

    /**
     * Publish app and generate a public share token
     */
    public App publishApp(Long appId, Long userId) {
        App app = appService.getAppByIdAndUser(appId, userId);
        if (app.getHtmlContent() == null || app.getHtmlContent().isBlank()) {
            throw BusinessException.of("应用还没有生成代码，无法发布");
        }
        // Generate unique share token
        String token = RandomUtil.randomString(12);
        String shareUrl = "http://localhost:" + serverPort + "/share/" + token;

        app.setStatus("PUBLISHED");
        app.setShareUrl(shareUrl);
        app.setUpdatedAt(LocalDateTime.now());
        appMapper.updateById(app);
        return app;
    }

    /**
     * Get app by share token (for public access)
     */
    public App getByShareToken(String token) {
        String shareUrl = "http://localhost:" + serverPort + "/share/" + token;
        App app = appMapper.selectOne(
                new com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<App>()
                        .eq(App::getShareUrl, shareUrl));
        if (app == null)
            throw BusinessException.notFound("分享链接");
        return app;
    }

    /**
     * Fork an app (duplicate it for the current user)
     */
    public App forkApp(Long sourceAppId, Long userId) {
        App source = appService.getAppById(sourceAppId);
        App forked = new App();
        forked.setUserId(userId);
        forked.setTitle("Fork of " + source.getTitle());
        forked.setDescription(source.getDescription());
        forked.setPrompt(source.getPrompt());
        forked.setHtmlContent(source.getHtmlContent());
        forked.setCssContent(source.getCssContent());
        forked.setJsContent(source.getJsContent());
        forked.setStatus("DONE");
        forked.setIsFeatured(false);
        forked.setCreatedAt(LocalDateTime.now());
        forked.setUpdatedAt(LocalDateTime.now());
        appMapper.insert(forked);
        return forked;
    }

    /**
     * Get app for download (owner or published)
     */
    public App getAppForDownload(Long appId, Long userId) {
        App app = appService.getAppById(appId);
        if (!app.getUserId().equals(userId) && !"PUBLISHED".equals(app.getStatus())) {
            throw BusinessException.forbidden();
        }
        return app;
    }

    /**
     * Get app for embed view (public)
     */
    public App getAppForEmbed(Long appId) {
        return appService.getAppById(appId);
    }

    /**
     * Build full preview HTML (HTML + embedded CSS + JS)
     */
    public String buildPreviewHtml(App app) {
        String html = app.getHtmlContent() != null ? app.getHtmlContent()
                : "<html><body><p>No content</p></body></html>";
        if (app.getCssContent() != null && !app.getCssContent().isBlank()) {
            html = html.replace("</head>", "<style>" + app.getCssContent() + "</style></head>");
        }
        if (app.getJsContent() != null && !app.getJsContent().isBlank()) {
            html = html.replace("</body>", "<script>" + app.getJsContent() + "</script></body>");
        }
        return html;
    }

    /**
     * Package app into zip file (HTML + CSS + JS)
     */
    public byte[] buildZip(App app) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try (ZipOutputStream zos = new ZipOutputStream(baos)) {
            // index.html (with linked CSS and JS)
            String html = buildLinkedHtml(app);
            addZipEntry(zos, "index.html", html.getBytes());

            if (app.getCssContent() != null && !app.getCssContent().isBlank()) {
                addZipEntry(zos, "style.css", app.getCssContent().getBytes());
            }
            if (app.getJsContent() != null && !app.getJsContent().isBlank()) {
                addZipEntry(zos, "script.js", app.getJsContent().getBytes());
            }

            // README
            String readme = "# " + app.getTitle() + "\n\n"
                    + "Generated by AI Code Platform\n\n"
                    + "## 使用方法\n直接用浏览器打开 index.html 即可。\n\n"
                    + "## 原始需求\n" + (app.getPrompt() != null ? app.getPrompt() : "");
            addZipEntry(zos, "README.md", readme.getBytes());
        }
        return baos.toByteArray();
    }

    private String buildLinkedHtml(App app) {
        String html = app.getHtmlContent() != null ? app.getHtmlContent() : "<html><head></head><body></body></html>";
        if (app.getCssContent() != null && !app.getCssContent().isBlank()) {
            html = html.replace("</head>", "<link rel=\"stylesheet\" href=\"style.css\">\n</head>");
        }
        if (app.getJsContent() != null && !app.getJsContent().isBlank()) {
            html = html.replace("</body>", "<script src=\"script.js\"></script>\n</body>");
        }
        return html;
    }

    private void addZipEntry(ZipOutputStream zos, String name, byte[] data) throws IOException {
        ZipEntry entry = new ZipEntry(name);
        zos.putNextEntry(entry);
        zos.write(data);
        zos.closeEntry();
    }
}
